##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  周四 9月 24 15:51:11 2020
##  Generated by MIG Version 4.0
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX690T-FFG1761
##                    Speedgrade:        -3
##                    Design Entry:      VERILOG
##                    Frequency:         500 MHz
##                    Time Period:       2000 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: QDRIIPLUS_SRAM->Components-BL4->CY7C25652KV18-500BZC
## Data Width: 36
## Time Period: 2000
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################


# PadFunction: IO_L4P_T0_35 
set_property VCCAUX_IO DONTCARE [get_ports {init_calib_complete}]
set_property IOSTANDARD LVCMOS18 [get_ports {init_calib_complete}]
set_property PACKAGE_PIN A35 [get_ports {init_calib_complete}]

# PadFunction: IO_L2P_T0_19 
set_property VCCAUX_IO DONTCARE [get_ports {tg_compare_error}]
set_property IOSTANDARD LVCMOS18 [get_ports {tg_compare_error}]
set_property PACKAGE_PIN A40 [get_ports {tg_compare_error}]

