##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  周四 9月 24 15:51:11 2020
##  Generated by MIG Version 4.0
##  
##################################################################################################
##  File name :       mig_7a_0.xdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX690T-FFG1761
##                    Speedgrade:        -3
##                    Design Entry:      VERILOG
##                    Frequency:         500 MHz
##                    Time Period:       2000 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: QDRIIPLUS_SRAM->Components-BL4->CY7C25652KV18-500BZC
## Data Width: 36
## Time Period: 2000
## Data Mask: 1
##################################################################################################

create_clock -period 2.999 [get_ports sys_clk_p]
          
create_clock -period 5 [get_ports clk_ref_p]
          
create_clock -period 2 [get_ports {qdriip_cq_p[*] qdriip_cq_n[*]}]
          
############## NET - IOSTANDARD ##################


# PadFunction: IO_L1P_T0_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[0]}]
set_property SLEW FAST [get_ports {qdriip_d[0]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[0]}]
set_property PACKAGE_PIN A24 [get_ports {qdriip_d[0]}]

# PadFunction: IO_L1N_T0_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[1]}]
set_property SLEW FAST [get_ports {qdriip_d[1]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[1]}]
set_property PACKAGE_PIN A25 [get_ports {qdriip_d[1]}]

# PadFunction: IO_L2P_T0_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[2]}]
set_property SLEW FAST [get_ports {qdriip_d[2]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[2]}]
set_property PACKAGE_PIN B22 [get_ports {qdriip_d[2]}]

# PadFunction: IO_L2N_T0_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[3]}]
set_property SLEW FAST [get_ports {qdriip_d[3]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[3]}]
set_property PACKAGE_PIN A22 [get_ports {qdriip_d[3]}]

# PadFunction: IO_L4P_T0_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[4]}]
set_property SLEW FAST [get_ports {qdriip_d[4]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[4]}]
set_property PACKAGE_PIN C23 [get_ports {qdriip_d[4]}]

# PadFunction: IO_L4N_T0_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[5]}]
set_property SLEW FAST [get_ports {qdriip_d[5]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[5]}]
set_property PACKAGE_PIN B23 [get_ports {qdriip_d[5]}]

# PadFunction: IO_L5P_T0_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[6]}]
set_property SLEW FAST [get_ports {qdriip_d[6]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[6]}]
set_property PACKAGE_PIN B26 [get_ports {qdriip_d[6]}]

# PadFunction: IO_L5N_T0_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[7]}]
set_property SLEW FAST [get_ports {qdriip_d[7]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[7]}]
set_property PACKAGE_PIN B27 [get_ports {qdriip_d[7]}]

# PadFunction: IO_L6P_T0_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[8]}]
set_property SLEW FAST [get_ports {qdriip_d[8]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[8]}]
set_property PACKAGE_PIN C24 [get_ports {qdriip_d[8]}]

# PadFunction: IO_L8P_T1_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[9]}]
set_property SLEW FAST [get_ports {qdriip_d[9]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[9]}]
set_property PACKAGE_PIN F22 [get_ports {qdriip_d[9]}]

# PadFunction: IO_L8N_T1_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[10]}]
set_property SLEW FAST [get_ports {qdriip_d[10]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[10]}]
set_property PACKAGE_PIN E22 [get_ports {qdriip_d[10]}]

# PadFunction: IO_L9P_T1_DQS_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[11]}]
set_property SLEW FAST [get_ports {qdriip_d[11]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[11]}]
set_property PACKAGE_PIN F25 [get_ports {qdriip_d[11]}]

# PadFunction: IO_L9N_T1_DQS_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[12]}]
set_property SLEW FAST [get_ports {qdriip_d[12]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[12]}]
set_property PACKAGE_PIN E25 [get_ports {qdriip_d[12]}]

# PadFunction: IO_L10P_T1_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[13]}]
set_property SLEW FAST [get_ports {qdriip_d[13]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[13]}]
set_property PACKAGE_PIN D22 [get_ports {qdriip_d[13]}]

# PadFunction: IO_L10N_T1_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[14]}]
set_property SLEW FAST [get_ports {qdriip_d[14]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[14]}]
set_property PACKAGE_PIN D23 [get_ports {qdriip_d[14]}]

# PadFunction: IO_L11P_T1_SRCC_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[15]}]
set_property SLEW FAST [get_ports {qdriip_d[15]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[15]}]
set_property PACKAGE_PIN D25 [get_ports {qdriip_d[15]}]

# PadFunction: IO_L11N_T1_SRCC_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[16]}]
set_property SLEW FAST [get_ports {qdriip_d[16]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[16]}]
set_property PACKAGE_PIN D26 [get_ports {qdriip_d[16]}]

# PadFunction: IO_L12P_T1_MRCC_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[17]}]
set_property SLEW FAST [get_ports {qdriip_d[17]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[17]}]
set_property PACKAGE_PIN C25 [get_ports {qdriip_d[17]}]

# PadFunction: IO_L14P_T2_SRCC_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[18]}]
set_property SLEW FAST [get_ports {qdriip_d[18]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[18]}]
set_property PACKAGE_PIN C28 [get_ports {qdriip_d[18]}]

# PadFunction: IO_L14N_T2_SRCC_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[19]}]
set_property SLEW FAST [get_ports {qdriip_d[19]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[19]}]
set_property PACKAGE_PIN C29 [get_ports {qdriip_d[19]}]

# PadFunction: IO_L15N_T2_DQS_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[20]}]
set_property SLEW FAST [get_ports {qdriip_d[20]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[20]}]
set_property PACKAGE_PIN B29 [get_ports {qdriip_d[20]}]

# PadFunction: IO_L16P_T2_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[21]}]
set_property SLEW FAST [get_ports {qdriip_d[21]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[21]}]
set_property PACKAGE_PIN A31 [get_ports {qdriip_d[21]}]

# PadFunction: IO_L16N_T2_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[22]}]
set_property SLEW FAST [get_ports {qdriip_d[22]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[22]}]
set_property PACKAGE_PIN A32 [get_ports {qdriip_d[22]}]

# PadFunction: IO_L17P_T2_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[23]}]
set_property SLEW FAST [get_ports {qdriip_d[23]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[23]}]
set_property PACKAGE_PIN A29 [get_ports {qdriip_d[23]}]

# PadFunction: IO_L17N_T2_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[24]}]
set_property SLEW FAST [get_ports {qdriip_d[24]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[24]}]
set_property PACKAGE_PIN A30 [get_ports {qdriip_d[24]}]

# PadFunction: IO_L18P_T2_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[25]}]
set_property SLEW FAST [get_ports {qdriip_d[25]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[25]}]
set_property PACKAGE_PIN C31 [get_ports {qdriip_d[25]}]

# PadFunction: IO_L18N_T2_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[26]}]
set_property SLEW FAST [get_ports {qdriip_d[26]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[26]}]
set_property PACKAGE_PIN B31 [get_ports {qdriip_d[26]}]

# PadFunction: IO_L19N_T3_VREF_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[27]}]
set_property SLEW FAST [get_ports {qdriip_d[27]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[27]}]
set_property PACKAGE_PIN D31 [get_ports {qdriip_d[27]}]

# PadFunction: IO_L20P_T3_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[28]}]
set_property SLEW FAST [get_ports {qdriip_d[28]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[28]}]
set_property PACKAGE_PIN D30 [get_ports {qdriip_d[28]}]

# PadFunction: IO_L20N_T3_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[29]}]
set_property SLEW FAST [get_ports {qdriip_d[29]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[29]}]
set_property PACKAGE_PIN C30 [get_ports {qdriip_d[29]}]

# PadFunction: IO_L21P_T3_DQS_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[30]}]
set_property SLEW FAST [get_ports {qdriip_d[30]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[30]}]
set_property PACKAGE_PIN E27 [get_ports {qdriip_d[30]}]

# PadFunction: IO_L21N_T3_DQS_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[31]}]
set_property SLEW FAST [get_ports {qdriip_d[31]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[31]}]
set_property PACKAGE_PIN E28 [get_ports {qdriip_d[31]}]

# PadFunction: IO_L22P_T3_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[32]}]
set_property SLEW FAST [get_ports {qdriip_d[32]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[32]}]
set_property PACKAGE_PIN F29 [get_ports {qdriip_d[32]}]

# PadFunction: IO_L22N_T3_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[33]}]
set_property SLEW FAST [get_ports {qdriip_d[33]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[33]}]
set_property PACKAGE_PIN E29 [get_ports {qdriip_d[33]}]

# PadFunction: IO_L23P_T3_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[34]}]
set_property SLEW FAST [get_ports {qdriip_d[34]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[34]}]
set_property PACKAGE_PIN F26 [get_ports {qdriip_d[34]}]

# PadFunction: IO_L23N_T3_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_d[35]}]
set_property SLEW FAST [get_ports {qdriip_d[35]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_d[35]}]
set_property PACKAGE_PIN F27 [get_ports {qdriip_d[35]}]

# PadFunction: IO_L1P_T0_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[0]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[0]}]
set_property PACKAGE_PIN C16 [get_ports {qdriip_q[0]}]

# PadFunction: IO_L1N_T0_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[1]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[1]}]
set_property PACKAGE_PIN B16 [get_ports {qdriip_q[1]}]

# PadFunction: IO_L2P_T0_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[2]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[2]}]
set_property PACKAGE_PIN B14 [get_ports {qdriip_q[2]}]

# PadFunction: IO_L2N_T0_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[3]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[3]}]
set_property PACKAGE_PIN A14 [get_ports {qdriip_q[3]}]

# PadFunction: IO_L3P_T0_DQS_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[4]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[4]}]
set_property PACKAGE_PIN C15 [get_ports {qdriip_q[4]}]

# PadFunction: IO_L3N_T0_DQS_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[5]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[5]}]
set_property PACKAGE_PIN C14 [get_ports {qdriip_q[5]}]

# PadFunction: IO_L4P_T0_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[6]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[6]}]
set_property PACKAGE_PIN D13 [get_ports {qdriip_q[6]}]

# PadFunction: IO_L4N_T0_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[7]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[7]}]
set_property PACKAGE_PIN C13 [get_ports {qdriip_q[7]}]

# PadFunction: IO_L5P_T0_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[8]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[8]}]
set_property PACKAGE_PIN D16 [get_ports {qdriip_q[8]}]

# PadFunction: IO_L7P_T1_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[9]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[9]}]
set_property PACKAGE_PIN F16 [get_ports {qdriip_q[9]}]

# PadFunction: IO_L7N_T1_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[10]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[10]}]
set_property PACKAGE_PIN E15 [get_ports {qdriip_q[10]}]

# PadFunction: IO_L8P_T1_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[11]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[11]}]
set_property PACKAGE_PIN E14 [get_ports {qdriip_q[11]}]

# PadFunction: IO_L8N_T1_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[12]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[12]}]
set_property PACKAGE_PIN E13 [get_ports {qdriip_q[12]}]

# PadFunction: IO_L9P_T1_DQS_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[13]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[13]}]
set_property PACKAGE_PIN H16 [get_ports {qdriip_q[13]}]

# PadFunction: IO_L9N_T1_DQS_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[14]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[14]}]
set_property PACKAGE_PIN G16 [get_ports {qdriip_q[14]}]

# PadFunction: IO_L10P_T1_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[15]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[15]}]
set_property PACKAGE_PIN G12 [get_ports {qdriip_q[15]}]

# PadFunction: IO_L10N_T1_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[16]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[16]}]
set_property PACKAGE_PIN F12 [get_ports {qdriip_q[16]}]

# PadFunction: IO_L12N_T1_MRCC_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[17]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[17]}]
set_property PACKAGE_PIN G13 [get_ports {qdriip_q[17]}]

# PadFunction: IO_L13N_T2_MRCC_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[18]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[18]}]
set_property PACKAGE_PIN H14 [get_ports {qdriip_q[18]}]

# PadFunction: IO_L15P_T2_DQS_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[19]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[19]}]
set_property PACKAGE_PIN K12 [get_ports {qdriip_q[19]}]

# PadFunction: IO_L15N_T2_DQS_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[20]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[20]}]
set_property PACKAGE_PIN J12 [get_ports {qdriip_q[20]}]

# PadFunction: IO_L16P_T2_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[21]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[21]}]
set_property PACKAGE_PIN K15 [get_ports {qdriip_q[21]}]

# PadFunction: IO_L16N_T2_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[22]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[22]}]
set_property PACKAGE_PIN J15 [get_ports {qdriip_q[22]}]

# PadFunction: IO_L17P_T2_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[23]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[23]}]
set_property PACKAGE_PIN K14 [get_ports {qdriip_q[23]}]

# PadFunction: IO_L17N_T2_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[24]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[24]}]
set_property PACKAGE_PIN K13 [get_ports {qdriip_q[24]}]

# PadFunction: IO_L18P_T2_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[25]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[25]}]
set_property PACKAGE_PIN L16 [get_ports {qdriip_q[25]}]

# PadFunction: IO_L18N_T2_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[26]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[26]}]
set_property PACKAGE_PIN L15 [get_ports {qdriip_q[26]}]

# PadFunction: IO_L19P_T3_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[27]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[27]}]
set_property PACKAGE_PIN L12 [get_ports {qdriip_q[27]}]

# PadFunction: IO_L20P_T3_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[28]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[28]}]
set_property PACKAGE_PIN M14 [get_ports {qdriip_q[28]}]

# PadFunction: IO_L20N_T3_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[29]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[29]}]
set_property PACKAGE_PIN L14 [get_ports {qdriip_q[29]}]

# PadFunction: IO_L21P_T3_DQS_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[30]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[30]}]
set_property PACKAGE_PIN N16 [get_ports {qdriip_q[30]}]

# PadFunction: IO_L21N_T3_DQS_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[31]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[31]}]
set_property PACKAGE_PIN M16 [get_ports {qdriip_q[31]}]

# PadFunction: IO_L22P_T3_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[32]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[32]}]
set_property PACKAGE_PIN N13 [get_ports {qdriip_q[32]}]

# PadFunction: IO_L22N_T3_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[33]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[33]}]
set_property PACKAGE_PIN M13 [get_ports {qdriip_q[33]}]

# PadFunction: IO_L23P_T3_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[34]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[34]}]
set_property PACKAGE_PIN N15 [get_ports {qdriip_q[34]}]

# PadFunction: IO_L23N_T3_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_q[35]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_q[35]}]
set_property PACKAGE_PIN N14 [get_ports {qdriip_q[35]}]

# PadFunction: IO_L13P_T2_MRCC_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[18]}]
set_property SLEW FAST [get_ports {qdriip_sa[18]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[18]}]
set_property PACKAGE_PIN H19 [get_ports {qdriip_sa[18]}]

# PadFunction: IO_L13N_T2_MRCC_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[17]}]
set_property SLEW FAST [get_ports {qdriip_sa[17]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[17]}]
set_property PACKAGE_PIN G18 [get_ports {qdriip_sa[17]}]

# PadFunction: IO_L14P_T2_SRCC_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[16]}]
set_property SLEW FAST [get_ports {qdriip_sa[16]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[16]}]
set_property PACKAGE_PIN K19 [get_ports {qdriip_sa[16]}]

# PadFunction: IO_L14N_T2_SRCC_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[15]}]
set_property SLEW FAST [get_ports {qdriip_sa[15]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[15]}]
set_property PACKAGE_PIN J18 [get_ports {qdriip_sa[15]}]

# PadFunction: IO_L15P_T2_DQS_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[14]}]
set_property SLEW FAST [get_ports {qdriip_sa[14]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[14]}]
set_property PACKAGE_PIN F20 [get_ports {qdriip_sa[14]}]

# PadFunction: IO_L15N_T2_DQS_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[13]}]
set_property SLEW FAST [get_ports {qdriip_sa[13]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[13]}]
set_property PACKAGE_PIN E20 [get_ports {qdriip_sa[13]}]

# PadFunction: IO_L16P_T2_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[12]}]
set_property SLEW FAST [get_ports {qdriip_sa[12]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[12]}]
set_property PACKAGE_PIN K17 [get_ports {qdriip_sa[12]}]

# PadFunction: IO_L16N_T2_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[11]}]
set_property SLEW FAST [get_ports {qdriip_sa[11]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[11]}]
set_property PACKAGE_PIN J17 [get_ports {qdriip_sa[11]}]

# PadFunction: IO_L17P_T2_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[10]}]
set_property SLEW FAST [get_ports {qdriip_sa[10]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[10]}]
set_property PACKAGE_PIN J20 [get_ports {qdriip_sa[10]}]

# PadFunction: IO_L17N_T2_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[9]}]
set_property SLEW FAST [get_ports {qdriip_sa[9]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[9]}]
set_property PACKAGE_PIN H20 [get_ports {qdriip_sa[9]}]

# PadFunction: IO_L18P_T2_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[8]}]
set_property SLEW FAST [get_ports {qdriip_sa[8]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[8]}]
set_property PACKAGE_PIN H18 [get_ports {qdriip_sa[8]}]

# PadFunction: IO_L18N_T2_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[7]}]
set_property SLEW FAST [get_ports {qdriip_sa[7]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[7]}]
set_property PACKAGE_PIN G17 [get_ports {qdriip_sa[7]}]

# PadFunction: IO_L19P_T3_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[6]}]
set_property SLEW FAST [get_ports {qdriip_sa[6]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[6]}]
set_property PACKAGE_PIN P18 [get_ports {qdriip_sa[6]}]

# PadFunction: IO_L19N_T3_VREF_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[5]}]
set_property SLEW FAST [get_ports {qdriip_sa[5]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[5]}]
set_property PACKAGE_PIN P17 [get_ports {qdriip_sa[5]}]

# PadFunction: IO_L20P_T3_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[4]}]
set_property SLEW FAST [get_ports {qdriip_sa[4]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[4]}]
set_property PACKAGE_PIN M17 [get_ports {qdriip_sa[4]}]

# PadFunction: IO_L20N_T3_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[3]}]
set_property SLEW FAST [get_ports {qdriip_sa[3]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[3]}]
set_property PACKAGE_PIN L17 [get_ports {qdriip_sa[3]}]

# PadFunction: IO_L21P_T3_DQS_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[2]}]
set_property SLEW FAST [get_ports {qdriip_sa[2]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[2]}]
set_property PACKAGE_PIN N19 [get_ports {qdriip_sa[2]}]

# PadFunction: IO_L21N_T3_DQS_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[1]}]
set_property SLEW FAST [get_ports {qdriip_sa[1]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[1]}]
set_property PACKAGE_PIN N18 [get_ports {qdriip_sa[1]}]

# PadFunction: IO_L22P_T3_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_sa[0]}]
set_property SLEW FAST [get_ports {qdriip_sa[0]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_sa[0]}]
set_property PACKAGE_PIN M19 [get_ports {qdriip_sa[0]}]

# PadFunction: IO_L22N_T3_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_w_n}]
set_property SLEW FAST [get_ports {qdriip_w_n}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_w_n}]
set_property PACKAGE_PIN M18 [get_ports {qdriip_w_n}]

# PadFunction: IO_L23P_T3_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_r_n}]
set_property SLEW FAST [get_ports {qdriip_r_n}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_r_n}]
set_property PACKAGE_PIN P20 [get_ports {qdriip_r_n}]

# PadFunction: IO_L23N_T3_38 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_dll_off_n}]
set_property SLEW FAST [get_ports {qdriip_dll_off_n}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_dll_off_n}]
set_property PACKAGE_PIN N20 [get_ports {qdriip_dll_off_n}]

# PadFunction: IO_L7P_T1_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_bw_n[0]}]
set_property SLEW FAST [get_ports {qdriip_bw_n[0]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_bw_n[0]}]
set_property PACKAGE_PIN E23 [get_ports {qdriip_bw_n[0]}]

# PadFunction: IO_L7N_T1_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_bw_n[1]}]
set_property SLEW FAST [get_ports {qdriip_bw_n[1]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_bw_n[1]}]
set_property PACKAGE_PIN E24 [get_ports {qdriip_bw_n[1]}]

# PadFunction: IO_L15P_T2_DQS_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_bw_n[2]}]
set_property SLEW FAST [get_ports {qdriip_bw_n[2]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_bw_n[2]}]
set_property PACKAGE_PIN B28 [get_ports {qdriip_bw_n[2]}]

# PadFunction: IO_L19P_T3_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_bw_n[3]}]
set_property SLEW FAST [get_ports {qdriip_bw_n[3]}]
set_property IOSTANDARD HSTL_I [get_ports {qdriip_bw_n[3]}]
set_property PACKAGE_PIN E30 [get_ports {qdriip_bw_n[3]}]

# PadFunction: IO_L13P_T2_MRCC_37 
set_property VCCAUX_IO DONTCARE [get_ports {sys_clk_p}]
set_property IOSTANDARD DIFF_HSTL_I [get_ports {sys_clk_p}]
set_property PACKAGE_PIN D27 [get_ports {sys_clk_p}]

# PadFunction: IO_L13N_T2_MRCC_37 
set_property VCCAUX_IO DONTCARE [get_ports {sys_clk_n}]
set_property IOSTANDARD DIFF_HSTL_I [get_ports {sys_clk_n}]
set_property PACKAGE_PIN D28 [get_ports {sys_clk_n}]

# PadFunction: IO_L12P_T1_MRCC_16 
set_property VCCAUX_IO DONTCARE [get_ports {clk_ref_p}]
set_property IOSTANDARD LVDS [get_ports {clk_ref_p}]
set_property PACKAGE_PIN AB33 [get_ports {clk_ref_p}]

# PadFunction: IO_L12N_T1_MRCC_16 
set_property VCCAUX_IO DONTCARE [get_ports {clk_ref_n}]
set_property IOSTANDARD LVDS [get_ports {clk_ref_n}]
set_property PACKAGE_PIN AC33 [get_ports {clk_ref_n}]

# PadFunction: IO_L2N_T0_AD12N_35 
set_property VCCAUX_IO DONTCARE [get_ports {sys_rst}]
set_property IOSTANDARD LVCMOS18 [get_ports {sys_rst}]
set_property PACKAGE_PIN A34 [get_ports {sys_rst}]

# PadFunction: IO_L12P_T1_MRCC_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_cq_p[0]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_cq_p[0]}]
set_property PACKAGE_PIN G14 [get_ports {qdriip_cq_p[0]}]

# PadFunction: IO_L13P_T2_MRCC_39 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_cq_n[0]}]
set_property IOSTANDARD HSTL_I_DCI [get_ports {qdriip_cq_n[0]}]
set_property PACKAGE_PIN H15 [get_ports {qdriip_cq_n[0]}]

# PadFunction: IO_L3P_T0_DQS_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_k_p[0]}]
set_property SLEW FAST [get_ports {qdriip_k_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II [get_ports {qdriip_k_p[0]}]
set_property PACKAGE_PIN A26 [get_ports {qdriip_k_p[0]}]

# PadFunction: IO_L3N_T0_DQS_37 
set_property VCCAUX_IO NORMAL [get_ports {qdriip_k_n[0]}]
set_property SLEW FAST [get_ports {qdriip_k_n[0]}]
set_property IOSTANDARD DIFF_HSTL_II [get_ports {qdriip_k_n[0]}]
set_property PACKAGE_PIN A27 [get_ports {qdriip_k_n[0]}]



set_property LOC PHASER_OUT_PHY_X1Y31 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_D.qdr_rld_byte_lane_D/PHASER_OUT_inst.phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y30 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_C.qdr_rld_byte_lane_C/PHASER_OUT_inst.phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y29 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_B.qdr_rld_byte_lane_B/PHASER_OUT_inst.phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y28 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_A.qdr_rld_byte_lane_A/PHASER_OUT_inst.phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y33 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_1.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_B.qdr_rld_byte_lane_B/PHASER_OUT_inst.phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y32 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_1.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_A.qdr_rld_byte_lane_A/PHASER_OUT_inst.phaser_out}]

set_property LOC PHASER_IN_PHY_X1Y39 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_0.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_D.qdr_rld_byte_lane_D/PHASER_IN_inst.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y38 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_0.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_C.qdr_rld_byte_lane_C/PHASER_IN_inst.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y37 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_0.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_B.qdr_rld_byte_lane_B/PHASER_IN_inst.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y36 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_0.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_A.qdr_rld_byte_lane_A/PHASER_IN_inst.phaser_in}]

set_property LOC OUT_FIFO_X1Y31 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_D.qdr_rld_byte_lane_D/out_fifo_inst.out_fifo}]
set_property LOC OUT_FIFO_X1Y30 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_C.qdr_rld_byte_lane_C/out_fifo_inst.out_fifo}]
set_property LOC OUT_FIFO_X1Y29 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_B.qdr_rld_byte_lane_B/out_fifo_inst.out_fifo}]
set_property LOC OUT_FIFO_X1Y28 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_A.qdr_rld_byte_lane_A/out_fifo_inst.out_fifo}]
set_property LOC OUT_FIFO_X1Y33 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_1.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_B.qdr_rld_byte_lane_B/out_fifo_inst.out_fifo}]
set_property LOC OUT_FIFO_X1Y32 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_1.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_A.qdr_rld_byte_lane_A/out_fifo_inst.out_fifo}]

set_property LOC IN_FIFO_X1Y39 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_0.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_D.qdr_rld_byte_lane_D/in_fifo_inst.in_fifo}]
set_property LOC IN_FIFO_X1Y38 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_0.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_C.qdr_rld_byte_lane_C/in_fifo_inst.in_fifo}]
set_property LOC IN_FIFO_X1Y37 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_0.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_B.qdr_rld_byte_lane_B/in_fifo_inst.in_fifo}]
set_property LOC IN_FIFO_X1Y36 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_0.u_qdr_rld_phy_4lanes/qdr_rld_byte_lane_A.qdr_rld_byte_lane_A/in_fifo_inst.in_fifo}]

set_property LOC PHY_CONTROL_X1Y7 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/PHY_CONTROL_INST.phy_control_i}]
set_property LOC PHY_CONTROL_X1Y8 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_1.u_qdr_rld_phy_4lanes/PHY_CONTROL_INST.phy_control_i}]

set_property LOC PHASER_REF_X1Y7 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_2.u_qdr_rld_phy_4lanes/phaser_ref_i}]
set_property LOC PHASER_REF_X1Y8 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_1.u_qdr_rld_phy_4lanes/phaser_ref_i}]
set_property LOC PHASER_REF_X1Y9 [get_cells  -hier -filter {NAME =~ */qdr_rld_phy_4lanes_0.u_qdr_rld_phy_4lanes/phaser_ref_i}]

set_property LOC PLLE2_ADV_X1Y7 [get_cells -hier -filter {NAME =~ */u_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X1Y7 [get_cells -hier -filter {NAME =~ */u_infrastructure/gen_mmcm.mmcm_i}]



set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -setup 2 -start
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 3
set_false_path -through [get_nets */sys_rst]
          