###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  周四 9月 24 15:51:11 2020
##  Generated by MIG Version 4.0
##  
##################################################################################################
##  File name :       mig_7a_0.xdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX690T-FFG1761
##                    Speedgrade:        -3
##                    Design Entry:      VERILOG
##                    Frequency:         500 MHz
##                    Time Period:       2000 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: QDRIIPLUS_SRAM->Components-BL4->CY7C25652KV18-500BZC
## Data Width: 36
## Time Period: 2000
## Data Mask: 1
##################################################################################################